// Auto-generated by storyboard/build_video.py — DO NOT EDIT BY HAND.
// Contains only the active project's scenes. Rewritten on every build.
//
// Read by remotion/src/Root.tsx + UniversalScenePreview.tsx.

export type SceneTimeline = {
  id: string;
  durationFrames: number;
  durationSeconds: number;
  fps: number;
  audioFile: string;
  anchors: Record<string, number>;
  phases: Array<{
    id: string;
    fromFrame: number;
    toFrame: number;
    enterFrames: number;
    exitFrames: number;
    transitionIn: string;
  }>;
};

export const TIMELINES: Record<string, SceneTimeline> = {
  "chat-5-5-s01": {
    "id": "chat-5-5-s01",
    "durationFrames": 1489,
    "durationSeconds": 49.633,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 1489,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s02": {
    "id": "chat-5-5-s02",
    "durationFrames": 1119,
    "durationSeconds": 37.3,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 1119,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s03": {
    "id": "chat-5-5-s03",
    "durationFrames": 2874,
    "durationSeconds": 95.8,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 2874,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s04": {
    "id": "chat-5-5-s04",
    "durationFrames": 4649,
    "durationSeconds": 154.967,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 4649,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s05": {
    "id": "chat-5-5-s05",
    "durationFrames": 7701,
    "durationSeconds": 256.7,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 7701,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s06": {
    "id": "chat-5-5-s06",
    "durationFrames": 5534,
    "durationSeconds": 184.467,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 5534,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s07": {
    "id": "chat-5-5-s07",
    "durationFrames": 3402,
    "durationSeconds": 113.4,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 3402,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s08": {
    "id": "chat-5-5-s08",
    "durationFrames": 4299,
    "durationSeconds": 143.3,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 4299,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s09": {
    "id": "chat-5-5-s09",
    "durationFrames": 11,
    "durationSeconds": 0.367,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 11,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s10": {
    "id": "chat-5-5-s10",
    "durationFrames": 8863,
    "durationSeconds": 295.433,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 8863,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  }
};
