// Auto-generated by storyboard/build_video.py — DO NOT EDIT BY HAND.
// Contains only the active project's scenes. Rewritten on every build.
//
// Read by remotion/src/Root.tsx + UniversalScenePreview.tsx.

export type SceneTimeline = {
  id: string;
  durationFrames: number;
  durationSeconds: number;
  fps: number;
  audioFile: string;
  anchors: Record<string, number>;
  phases: Array<{
    id: string;
    fromFrame: number;
    toFrame: number;
    enterFrames: number;
    exitFrames: number;
    transitionIn: string;
  }>;
};

export const TIMELINES: Record<string, SceneTimeline> = {
  "chat-5-5-s01": {
    "id": "chat-5-5-s01",
    "durationFrames": 1172,
    "durationSeconds": 39.067,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 1172,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s02": {
    "id": "chat-5-5-s02",
    "durationFrames": 854,
    "durationSeconds": 28.467,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 854,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s03": {
    "id": "chat-5-5-s03",
    "durationFrames": 2121,
    "durationSeconds": 70.7,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 2121,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s04": {
    "id": "chat-5-5-s04",
    "durationFrames": 3379,
    "durationSeconds": 112.633,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 3379,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s05": {
    "id": "chat-5-5-s05",
    "durationFrames": 5711,
    "durationSeconds": 190.367,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 5711,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s06": {
    "id": "chat-5-5-s06",
    "durationFrames": 4132,
    "durationSeconds": 137.733,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 4132,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s07": {
    "id": "chat-5-5-s07",
    "durationFrames": 2868,
    "durationSeconds": 95.6,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 2868,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s08": {
    "id": "chat-5-5-s08",
    "durationFrames": 3544,
    "durationSeconds": 118.133,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 3544,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s09": {
    "id": "chat-5-5-s09",
    "durationFrames": 3475,
    "durationSeconds": 115.833,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 3475,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  },
  "chat-5-5-s10": {
    "id": "chat-5-5-s10",
    "durationFrames": 2868,
    "durationSeconds": 95.6,
    "fps": 30,
    "audioFile": "vo-chat_5_5-full.mp3",
    "anchors": {},
    "phases": [
      {
        "id": "scene",
        "fromFrame": 0,
        "toFrame": 2868,
        "enterFrames": 0,
        "exitFrames": 0,
        "transitionIn": "hard_cut"
      }
    ]
  }
};
