const NARRATION_TEXT = "Here is the data. Two charts. One story. For complex tasks \u2014 the ones that genuinely require multi-step reasoning \u2014 high effort helps.";
const w=width,h=height;
const bd=React.createElement(AbsoluteFill,{style:{backgroundColor:D.bg,opacity:interpolate(frame,[0,8],[0,1],{extrapolateRight:'clamp'})}});
const op=interpolate(frame,[0,20],[0,1],{extrapolateRight:'clamp'});
const pw=Math.round(w*0.40),ph=Math.round(h*0.66),pt=Math.round(h*0.12);
const lx=Math.round(w*0.04),rx=Math.round(w*0.56);
const leftBorder=React.createElement('div',{style:{position:'absolute',left:lx,top:pt,width:pw,height:ph,border:'2px solid '+D.amber,borderRadius:10,backgroundColor:D.surface,opacity:op}});
const leftHdr=React.createElement('div',{style:{position:'absolute',left:lx,top:pt+Math.round(h*0.025),width:pw,textAlign:'center',color:D.amber,fontFamily:D.font_mono,fontSize:Math.round(w*0.013),fontWeight:'900',letterSpacing:'0.12em',opacity:op}},'COMPLEX TASKS');
const rightBorder=React.createElement('div',{style:{position:'absolute',left:rx,top:pt,width:pw,height:ph,border:'2px solid '+D.green,borderRadius:10,backgroundColor:D.surface,opacity:op}});
const rightHdr=React.createElement('div',{style:{position:'absolute',left:rx,top:pt+Math.round(h*0.025),width:pw,textAlign:'center',color:D.green,fontFamily:D.font_mono,fontSize:Math.round(w*0.013),fontWeight:'900',letterSpacing:'0.12em',opacity:op}},'SIMPLE TASKS');
const barLabelY=pt+ph+Math.round(h*0.015);
const barW=Math.round(pw*0.32);
const cLowX=lx+Math.round(pw*0.08),cHighX=lx+Math.round(pw*0.54);
const sLowX=rx+Math.round(pw*0.08),sHighX=rx+Math.round(pw*0.54);
const lblStyle={fontFamily:D.font_mono,fontSize:Math.round(w*0.009),textAlign:'center',opacity:op,color:D.text_dim};
const cLowL=React.createElement('div',{style:{position:'absolute',left:cLowX,top:barLabelY,width:barW,...lblStyle}},'LOW');
const cHighL=React.createElement('div',{style:{position:'absolute',left:cHighX,top:barLabelY,width:barW,...lblStyle}},'HIGH');
const sLowL=React.createElement('div',{style:{position:'absolute',left:sLowX,top:barLabelY,width:barW,...lblStyle}},'LOW');
const sHighL=React.createElement('div',{style:{position:'absolute',left:sHighX,top:barLabelY,width:barW,...lblStyle}},'HIGH');
const si=React.createElement('div',{style:{position:'absolute',top:Math.round(h*0.03),left:Math.round(w*0.03),color:D.text_dim,fontFamily:D.font_mono,fontSize:Math.round(w*0.008),opacity:0.6}},'S4');
return [bd,si,leftBorder,leftHdr,rightBorder,rightHdr,cLowL,cHighL,sLowL,sHighL];