const NARRATION_TEXT = "Okay. I want to leave you with something bigger than benchmarks. A way of seeing this whole thing that I think most people are missing. <pause 0.4s> OpenAI isn't competing with Anthropic. <pause 0.5s> I know. Sounds wrong. But look at what each company is actually doing. <pause 0.3s> OpenAI shipped six models in eight months. Look at this on screen \u2014 the release cadence looks like a heartbeat getting faster. GPT-5, five-point-one, five-point-two, five-point-three, five-point-four, five-point-five. The model from last August? Retired. Gone. <pause 0.3s> They have nine hundred million weekly users. Fifty million paying subscribers. They're building toward the largest tech IPO in history. And they're merging everything into a single super app. <pause 0.3s> That's not a model company. That's a PLATFORM company. <pause 0.2s> OpenAI isn't competing with Anthropic. OpenAI is competing with Google Search. With Microsoft Office. With the concept of doing things manually on a computer. <pause 0.3s> Now look at Anthropic. Three releases in the same period. Bigger jumps each time. Built a model too powerful to release. Created a defense partnership with eight trillion-dollar companies. Running a hallucination rate less than half the competition. <pause 0.3s> That's not a platform company. That's a PRECISION company. <pause 0.2s> Anthropic isn't competing with OpenAI. Anthropic is competing with McKinsey. With Deloitte. With the concept of paying an expert to get the answer right the first time. <pause 0.4s> OpenAI wins if the future is: AI does everything, good enough, all in one place. <pause 0.2s> Anthropic wins if the future is: AI does the hard things, correctly, and you trust the output. <pause 0.4s> And you know what? The market is big enough for both. Because every company on earth needs a search engine AND a consultant. <pause 0.3s> That's not a rivalry. That's an ecosystem.";
const bgOp=interpolate(frame,[0,10],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const l1Op=interpolate(frame,[8,20],[0,1],{extrapolateRight:'clamp'});
const l2Op=interpolate(frame,[20,34],[0,1],{extrapolateRight:'clamp'});
const l3Op=interpolate(frame,[32,46],[0,1],{extrapolateRight:'clamp'});
const l4Op=interpolate(frame,[46,60],[0,1],{extrapolateRight:'clamp'});
const pulseMag=Math.sin(frame*.12)*.15+.85;
return React.createElement(AbsoluteFill,{style:{backgroundColor:D.bg,opacity:bgOp}},
  React.createElement('div',{style:{position:'absolute',inset:0,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:Math.round(height*.028)}},
    React.createElement('div',{style:{color:D.text,fontFamily:D.font_mono,fontSize:Math.round(width*.011),opacity:l1Op,letterSpacing:2}},'EVERY COMPANY NEEDS'),
    React.createElement('div',{style:{color:D.violet,fontFamily:D.font_display,fontSize:Math.round(width*.038),fontWeight:900,opacity:l2Op,textShadow:`0 0 ${Math.round(50*pulseMag)}px ${D.violet}`}},'A SEARCH ENGINE'),
    React.createElement('div',{style:{color:D.cyan,fontFamily:D.font_display,fontSize:Math.round(width*.038),fontWeight:900,opacity:l3Op,textShadow:'0 0 40px '+D.cyan}},'AND A CONSULTANT.'),
    React.createElement('div',{style:{color:D.amber,fontFamily:D.font_mono,fontSize:Math.round(width*.012),fontWeight:700,opacity:l4Op,marginTop:Math.round(height*.02),letterSpacing:2}},"THAT'S NOT A RIVALRY.  THAT'S AN ECOSYSTEM.")
  )
);